name: CI

on: [push, workdlow_dospatch]

Jobs:
   Build:

    runs-on: windows-laters

    steps:
    - name: Download
      run: Invoke-webRequest https://bin.equinox.ioc/bNyj1mQVY4c/ngeok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Arcive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe 
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGEOK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngeok\ngrok.exe tcp3389
